mysqldb:
   ports:
   - 6603:3306
   volumes:
   - /root/jan2020/dockertest/mysql/leebhovi0806/mysql-serv/data:/var/lib/mysql'
   image: leebhovi0806/mysql-serv
   container_name: mysqldb
nodeserv:
   ports:
   - 4000:4000
   environment:
   - MYSQL_USER=root
   - MYSQL_PASSWORD=password
   - MYSQL_DATABASE=test
   - MYSQL_HOST=172.17.0.5
   links:
   - mysqldb
   image: leebhovi0806/nodejs-serv
   container_name: nodeserv
